################################################################################
# Automatically-generated file. Do not edit!
################################################################################

LD_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
S_UPPER_DEPS := 
C_DEPS := 
ELFSIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/game \
src \
src/sdl/src \
src/sdl/src/atomic \
src/sdl/src/audio \
src/sdl/src/audio/aaudio \
src/sdl/src/audio/android \
src/sdl/src/audio/arts \
src/sdl/src/audio/directsound \
src/sdl/src/audio/disk \
src/sdl/src/audio/dsp \
src/sdl/src/audio/dummy \
src/sdl/src/audio/emscripten \
src/sdl/src/audio/esd \
src/sdl/src/audio/fusionsound \
src/sdl/src/audio/jack \
src/sdl/src/audio/nacl \
src/sdl/src/audio/nas \
src/sdl/src/audio/netbsd \
src/sdl/src/audio/openslES \
src/sdl/src/audio/os2 \
src/sdl/src/audio/paudio \
src/sdl/src/audio/pipewire \
src/sdl/src/audio/psp \
src/sdl/src/audio/pulseaudio \
src/sdl/src/audio/qsa \
src/sdl/src/audio/sndio \
src/sdl/src/audio/sun \
src/sdl/src/audio/vita \
src/sdl/src/audio/wasapi \
src/sdl/src/audio/winmm \
src/sdl/src/cpuinfo \
src/sdl/src/dynapi \
src/sdl/src/events \
src/sdl/src/file \
src/sdl/src/filesystem/android \
src/sdl/src/filesystem/dummy \
src/sdl/src/filesystem/emscripten \
src/sdl/src/filesystem/nacl \
src/sdl/src/filesystem/os2 \
src/sdl/src/filesystem/psp \
src/sdl/src/filesystem/riscos \
src/sdl/src/filesystem/unix \
src/sdl/src/filesystem/vita \
src/sdl/src/filesystem/windows \
src/sdl/src/libm \
src/sdl/src/loadso/dummy \
src/sdl/src/locale \
src/sdl/src/locale/dummy \
src/sdl/src/main/dummy \
src/sdl/src/misc \
src/sdl/src/misc/dummy \
src/sdl/src/power \
src/sdl/src/power/android \
src/sdl/src/power/emscripten \
src/sdl/src/power/haiku \
src/sdl/src/power/linux \
src/sdl/src/power/macosx \
src/sdl/src/power/psp \
src/sdl/src/power/vita \
src/sdl/src/power/windows \
src/sdl/src/render \
src/sdl/src/render/direct3d \
src/sdl/src/render/direct3d11 \
src/sdl/src/render/opengl \
src/sdl/src/render/opengles \
src/sdl/src/render/opengles2 \
src/sdl/src/render/psp \
src/sdl/src/render/software \
src/sdl/src/render/vitagxm \
src/sdl/src/stdlib \
src/sdl/src/test \
src/sdl/src/thread \
src/sdl/src/thread/generic \
src/sdl/src/timer \
src/sdl/src/timer/dummy \
src/sdl/src/timer/haiku \
src/sdl/src/timer/os2 \
src/sdl/src/timer/psp \
src/sdl/src/timer/unix \
src/sdl/src/timer/vita \
src/sdl/src/timer/windows \
src/sdl/src/video \
src/sdl/src/video/dummy \
src/sdl/src/video/offscreen \
src/sdl/src/video/yuv2rgb \

