# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_accelerator_Blit1to2_0_0/design_1_accelerator_Blit1to2_0_0.xci
# IP: The module: 'design_1_accelerator_Blit1to2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_accelerator_Blit1to2_0_0/src/in_dw_conv_0/in_dw_conv_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==in_dw_conv_0 || ORIG_REF_NAME==in_dw_conv_0} -quiet] -quiet

# IP: F:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_accelerator_Blit1to2_0_0/design_1_accelerator_Blit1to2_0_0.xci
# IP: The module: 'design_1_accelerator_Blit1to2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_accelerator_Blit1to2_0_0/src/in_dw_conv_0/in_dw_conv_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==in_dw_conv_0 || ORIG_REF_NAME==in_dw_conv_0} -quiet] -quiet
