# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_key_driver_pb_0_0/design_1_key_driver_pb_0_0.xci
# IP: The module: 'design_1_key_driver_pb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_key_driver_pb_0_0/src/fifo_event_key/fifo_event_key.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_event_key || ORIG_REF_NAME==fifo_event_key} -quiet] -quiet

# XDC: f:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_key_driver_pb_0_0/src/fifo_event_key/fifo_event_key.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_event_key || ORIG_REF_NAME==fifo_event_key} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: F:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_key_driver_pb_0_0/design_1_key_driver_pb_0_0.xci
# IP: The module: 'design_1_key_driver_pb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_key_driver_pb_0_0/src/fifo_event_key/fifo_event_key.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_event_key || ORIG_REF_NAME==fifo_event_key} -quiet] -quiet

# XDC: f:/vivado_project/nexys_port_game_mb/nexys_port_game_mb.srcs/sources_1/bd/design_1/ip/design_1_key_driver_pb_0_0/src/fifo_event_key/fifo_event_key.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_event_key || ORIG_REF_NAME==fifo_event_key} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
