set_property PACKAGE_PIN E3 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN C4 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN D4 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]

set_property IOSTANDARD LVCMOS33 [get_ports {b_vga_s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_vga_s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_vga_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {b_vga_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_vga_s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_vga_s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_vga_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {g_vga_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_vga_s[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_vga_s[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_vga_s[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {r_vga_s[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports h_sync_vga]
set_property IOSTANDARD LVCMOS33 [get_ports v_sync_vga]
set_property PACKAGE_PIN A3 [get_ports {r_vga_s[0]}]
set_property PACKAGE_PIN B4 [get_ports {r_vga_s[1]}]
set_property PACKAGE_PIN C5 [get_ports {r_vga_s[2]}]
set_property PACKAGE_PIN A4 [get_ports {r_vga_s[3]}]
set_property PACKAGE_PIN C6 [get_ports {g_vga_s[0]}]
set_property PACKAGE_PIN A5 [get_ports {g_vga_s[1]}]
set_property PACKAGE_PIN B6 [get_ports {g_vga_s[2]}]
set_property PACKAGE_PIN A6 [get_ports {g_vga_s[3]}]
set_property PACKAGE_PIN B7 [get_ports {b_vga_s[0]}]
set_property PACKAGE_PIN C7 [get_ports {b_vga_s[1]}]
set_property PACKAGE_PIN D7 [get_ports {b_vga_s[2]}]
set_property PACKAGE_PIN D8 [get_ports {b_vga_s[3]}]
set_property PACKAGE_PIN B11 [get_ports h_sync_vga]
set_property PACKAGE_PIN B12 [get_ports v_sync_vga]







set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_tri_o[0]}]
set_property PACKAGE_PIN H17 [get_ports {GPIO_tri_o[0]}]
set_property PACKAGE_PIN K15 [get_ports {GPIO_tri_o[1]}]
set_property PACKAGE_PIN J13 [get_ports {GPIO_tri_o[2]}]
set_property PACKAGE_PIN N14 [get_ports {GPIO_tri_o[3]}]

set_property PACKAGE_PIN C12 [get_ports ext_reset_in]
set_property IOSTANDARD LVCMOS33 [get_ports ext_reset_in]

set_property PACKAGE_PIN N17 [get_ports btn_C]
set_property PACKAGE_PIN P18 [get_ports btn_D]
set_property PACKAGE_PIN P17 [get_ports btn_L]
set_property PACKAGE_PIN M17 [get_ports btn_R]
set_property PACKAGE_PIN M18 [get_ports btn_U]
set_property IOSTANDARD LVCMOS33 [get_ports btn_C]
set_property IOSTANDARD LVCMOS33 [get_ports btn_D]
set_property IOSTANDARD LVCMOS33 [get_ports btn_L]
set_property IOSTANDARD LVCMOS33 [get_ports btn_R]
set_property IOSTANDARD LVCMOS33 [get_ports btn_U]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/key_driver_pb_0/inst/key_driver_pb_v1_0_S00_AXI_inst/state_event[0]} {design_1_i/key_driver_pb_0/inst/key_driver_pb_v1_0_S00_AXI_inst/state_event[1]} {design_1_i/key_driver_pb_0/inst/key_driver_pb_v1_0_S00_AXI_inst/state_event[2]} {design_1_i/key_driver_pb_0/inst/key_driver_pb_v1_0_S00_AXI_inst/state_event[3]}]]

set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]

